# Generated by Django 2.2.11 on 2020-03-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0008_auto_20200328_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='poster',
            new_name='Poster',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='title',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='film',
            name='imdbID',
            field=models.CharField(default='', max_length=200),
        ),
    ]
