# Generated by Django 2.2.11 on 2020-03-28 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0006_myrating_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rated', models.CharField(max_length=200)),
                ('runtime', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=200)),
                ('plot', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('awards', models.CharField(max_length=200)),
                ('poster', models.CharField(max_length=1000)),
                ('metascore', models.CharField(max_length=200)),
                ('imdbRating', models.CharField(max_length=200)),
                ('imdbVotes', models.CharField(max_length=200)),
                ('imdbID', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('boxOffice', models.CharField(max_length=200)),
                ('production', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Film')),
            ],
        ),
    ]
