# Generated by Django 2.2.11 on 2020-04-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0014_auto_20200405_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='average',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
