# Generated by Django 2.2.11 on 2020-04-05 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('polls', '0018_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('average', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   to='contenttypes.ContentType')),
                ('film', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Film')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
