# Generated by Django 2.2.11 on 2020-04-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0021_auto_20200405_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrating',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
