# Generated by Django 2.2.11 on 2020-05-01 17:09

from django.db import migrations, models

from polls.models import Film


def set_my_defaults(apps, schema_editor):
    for film in Film.objects.all().iterator():
        film.imdbUrl = 'https://www.imdb.com/title/' + film.imdbID
        film.save()


def reverse_func(apps, schema_editor):
    pass  # code for reverting migration, if any


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0025_auto_20200501_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imdbUrl',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.RunPython(set_my_defaults, reverse_func),
        migrations.AlterField(
            model_name='film',
            name='imdbUrl',
            field=models.CharField(max_length=1000),
        ),
    ]
