# Generated by Django 2.2.11 on 2020-05-03 09:19
from django.db import migrations, models

from polls.actions.films.omdp import getByImdbID
from polls.models import Film


def set_my_defaults(apps, schema_editor):
    for film in Film.objects.all().iterator():
        data = getByImdbID(film.imdbID)
        film.plot = data['Plot']
        film.save()


def reverse_func(apps, schema_editor):
    pass  # code for reverting migration, if any


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0027_auto_20200501_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='plot',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.RunPython(set_my_defaults, reverse_func),
        migrations.AlterField(
            model_name='film',
            name='plot',
            field=models.CharField(max_length=1000),
        ),
    ]
