# Generated by Django 2.2.11 on 2020-05-03 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0028_film_plot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='plot',
            new_name='Plot',
        ),
    ]
