# Generated by Django 2.2.11 on 2020-06-01 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0031_auto_20200601_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
