# Generated by Django 2.2.11 on 2020-06-12 11:49

import RAKE
import django.db.models.deletion
from django.db import migrations, models

from polls.models import Film


def computeKeywords(text):
    rake = RAKE.Rake(RAKE.SmartStopList())
    keywords = rake.run(text, minCharacters=1, maxWords=3, minFrequency=1)
    result = str()
    for keyword in keywords:
        result += keyword[0]
        result += ","

    print(result)
    return result


def set_my_defaults(apps, schema_editor):
    for film in Film.objects.all().iterator():
        film.genre = computeKeywords(film.Plot)
        film.save()


def reverse_func(apps, schema_editor):
    pass  # code for reverting migration, if any


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0032_auto_20200601_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='keywords',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.RunPython(set_my_defaults, reverse_func),
        migrations.CreateModel(
            name='FilmQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField(default=0)),
                ('count', models.PositiveIntegerField(default=1)),
                ('fitness', models.FloatField(default=0)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Film')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
