# Generated by Django 2.2.11 on 2020-03-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0002_myrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrating',
            name='average',
            field=models.TextField(),
        ),
    ]
