# Generated by Django 2.2.11 on 2020-03-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0003_auto_20200324_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrating',
            name='average',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
