# Generated by Django 2.2.11 on 2020-03-24 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0004_auto_20200324_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myrating',
            name='average',
        ),
        migrations.RemoveField(
            model_name='myrating',
            name='foo',
        ),
    ]
