# Generated by Django 2.2.11 on 2020-03-28 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0007_film_globalratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='film',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='film',
            name='boxOffice',
        ),
        migrations.RemoveField(
            model_name='film',
            name='country',
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='film',
            name='imdbID',
        ),
        migrations.RemoveField(
            model_name='film',
            name='imdbRating',
        ),
        migrations.RemoveField(
            model_name='film',
            name='imdbVotes',
        ),
        migrations.RemoveField(
            model_name='film',
            name='language',
        ),
        migrations.RemoveField(
            model_name='film',
            name='metascore',
        ),
        migrations.RemoveField(
            model_name='film',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='film',
            name='production',
        ),
        migrations.RemoveField(
            model_name='film',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='film',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='film',
            name='type',
        ),
        migrations.RemoveField(
            model_name='film',
            name='website',
        ),
        migrations.RemoveField(
            model_name='film',
            name='writer',
        ),
        migrations.DeleteModel(
            name='GlobalRatings',
        ),
    ]
