# Generated by Django 2.2.11 on 2020-04-11 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0023_auto_20200405_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myrating',
            name='score',
        ),
        migrations.RemoveField(
            model_name='myrating',
            name='user',
        ),
    ]
